version: "3"
services:
  fullstack:
    build: images/19w18a/single
    environment:
      - FQDN=mail.localhost
      - DOMAIN=localhost
      - DB_HOST=db
      - DB_USER=mailuser
      - DB_PASSWORD=password
      - HOSTNAME=localhost
      - DB_NAME=email
      - DB_MAIL_USERNAME=mailer
      - DB_MAIL_PASSWORD=password
      - USE_LETSENCRYPT=no
      - USE_SELF_SIGNED=yes
    volumes:
      - "./mount/etc/postfix:/etc/postfix"
      - "./mount/etc/dovecot:/etc/dovecot"
      - "./mount/logs:/var/log"
    links:
      - db
  db:
    image: mysql/mysql-server
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=mailuser
      - MYSQL_PASSWORD=password
